apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: port-inv
    spec:
      containers:
        - name: minikube
          image: gcr.io/k8s-minikube/kicbase:v0.0.43
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-microservices
spec:
  selector:
    app: fastapi-microservices
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
